# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
android.nonTransitiveRClass=true
# Enables Compose compiler metrics (optional)
# kotlin.compiler.compose.metricsDestination=build/compose-metrics
# kotlin.compiler.compose.reportsDestination=build/compose-reports
